### ISSUE TITLE
Could you make a guide please?

### ISSUE THREAD

**Issue by SoFarHaveGoneHere** [msemple1111/kahoot-hack#12]
I'm new to coding and can't figure out how to use this kahoot hack. Could you make a detailed step by step guide on how to use this hack. Thanks!

**Comment by msemple1111** [comment]
It's pretty simple to set up: just install python, then download it and run

**Comment by SoFarHaveGoneHere** [comment]
Well I installed python, but now there is a python launcher and a python IDLE thing so which one do I use and what do I do with them?

**Comment by GhostGuild** [comment]
If you really need help with this then you shouldn't be using it.

**Comment by msemple1111** [comment]
open play.py or flood.py in IDLE (open IDLE then go [file], [open] ) . Then just goto [run], and [run module]. On screen instructions should follow.
