### ISSUE TITLE
"Game does not exist with that pin"

### ISSUE THREAD

**Issue by a11ce** [msemple1111/kahoot-hack#13]
Trying to use flood.py gives the error "Game does not exist with that pin." I can join the game fine manually.

**Comment by msemple1111** [comment]
What version of python are you using? (On terminal/ command prompt type: `python -V` )

**Comment by a11ce** [comment]
I fixed it, nevermind. Thank you!

**Comment by nmcc1212** [comment]
@a11ce how did you fix it
