### ISSUE TITLE
Invalid syntax

### ISSUE THREAD

**Issue by wihaueghfh** [msemple1111/kahoot-hack#14]
Hello

For some reason when I try to run the code in IDLE it has the invalid syntax error, could you please help?

thank you

**Comment by msemple1111** [comment]
you running python 3?

**Comment by wihaueghfh** [comment]
yes, Python three is open when I put the code in IDLE and run the module. (I also have the tab that runs kahoot and another tab that plays kahoot on the same browser, and yes the kahoot.it is playing the game being hosted by the other tab.)

**Comment by unixpickle** [comment]
You should elaborate on the error. For example, what line is it on?

**Comment by wihaueghfh** [comment]
there is only one line, the flood.py usage thing.

**Comment by Valerokai** [comment]
That line isn't the python script, clone the entire github repository, load up a command line then type that into the command line. Make sure you have python in your system path.

**Comment by wihaueghfh** [comment]
I think I get it, (sorry I dont much about coding) just a few questions. when you say command line, you mean in IDLE right? and I put this: https://github.com/msemple1111/kahoot-hack.git   in IDLE right?
once again, so sorry to take up your time

**Comment by Valerokai** [comment]
Your command line is usually your terminal emulator (CMD on Windows, Terminal on Mac, or whatever you prefer  on Linux) and you need to type into it
`git clone https://github.com/msemple1111/kahoot-hack.git`

`cd kahoot-hack`

`python play.py [insertname] `[insertpin]`

Replace [insertname] and [insertpin] with the name and pin of the game you wan't. If you get an error such as program or file cannot be find, you may need to add python to your path, which is really easy to do, and you can look up online how to do it.

Also if you don't know much about coding, I would recommend learning some python just to get familiar with the language, it's very useful for automating tasks even if you don't intend to get a job in programming.
