### ISSUE TITLE
Name is not defined

### ISSUE THREAD

**Issue by jaykm** [msemple1111/kahoot-hack#2]
Traceback (most recent call last):
  File "flood.py", line 36, in <module>
    pin, name, exc = get_input()
  File "flood.py", line 19, in get_input
    name = input("Please Enter the base name: ")
  File "<string>", line 1, in <module>
NameError: name 'jaykm' is not defined

**Comment by msemple1111** [comment]
run
```
git pull 
```

**Comment by jaykm** [comment]
I'm already up to date

**Comment by msemple1111** [comment]
@jaykm Your trying to use python 2, you must make sure you are running this tool using python 3.

If your on mac or linux, try:
```
python3 flood.py
```
If python 3 is installed

**Comment by msemple1111** [comment]
Im going to close this issue, if you need any more help - just comment again.
