### ISSUE TITLE
play.py is not working

### ISSUE THREAD

**Issue by makerstorage** [msemple1111/kahoot-hack#21]
I can not connect to a game.
Does kahoot change its handshake protocol frequently?

**Comment by unixpickle** [comment]
This should be fixed now. It was a bug in the service which deciphers hashes. That bug should now be fixed.

**Comment by nerginer** [comment]
Yes, It is working now. Thanks
I want to develop some code on this lib, but I want to be sure that it will work for a long time.
I only want to use the play.py
Do you think kahoot can change its service protocol and this library can be worthless

**Comment by unixpickle** [comment]
Kahoot has been known to change around their protocol to break various "hacks". However, this tool (and mine) have been around for years and we've always come back and fixed them. That said, I am sometimes slow to fix things if they break.

**Comment by nerginer** [comment]
Did you talk with kahoot to be an official api for them?

**Comment by unixpickle** [comment]
There's no way they would go for that. They have been specifically *trying* to break tools like this, especially with their challenge system.

**Comment by nerginer** [comment]
How can I reach you? I need your email address

**Comment by unixpickle** [comment]
My contact information is on my Github profile if you feel so inclined to have it, but I can't imagine why you would. Neither I, nor anybody else, are required to maintain or fix this project (and we are certainly not "on call" at all times). We do it for fun in our free time. If you need a reliable Kahoot API for a legitimate business, you should contact Kahoot and work out an agreement.

**Comment by unixpickle** [comment]
Also, you should close this issue, as it is fixed.

**Comment by nerginer** [comment]
I am asking for a cooperation on developing a kahoot related product.

**Comment by nerginer** [comment]
we can close this issue

**Comment by msemple1111** [comment]
Hi @makerstorage @nerginer I have an updated unreleased version of this project redesigned from scratch that is faster and more easily expandable that I intend to release within the coming months. If you would like to have a chat about it, my email is in my profile
