### ISSUE TITLE
Everything is Broken

### ISSUE THREAD

**Issue by CFPLanguage** [msemple1111/kahoot-hack#3]
When I run play.py and flood.py, I get this error message.
`Traceback (most recent call last):
  File "play.py", line 21, in <module>
    send.connect()
  File "main.py", line 255, in connect
    self.clientid = self.handshake()
  File "main.py", line 91, in handshake
    error(subId+100, str(r.status_code)+str(r.text),False)
NameError: name 'subId' is not defined`

**Comment by msemple1111** [comment]
It looks like they have changed the protocol recently. I will try and fix it on the weekend when I have some free time to commit.

**Comment by msemple1111** [comment]
@CFPLanguage It seems to be fixed after my last commit.

**Comment by nedla2004** [comment]
This seems to work, except when I run `flood.py` I get one user, not all that I wanted.

**Comment by msemple1111** [comment]
im not sure why, mine seems to work fine.

is there any errors? anything in the log.txt?

**Comment by nedla2004** [comment]
When I ran it again, it worked perfectly, sorry for the confusion.

**Comment by nedla2004** [comment]
I had entered a name that was already 15 characters long, so you could not add more on.
