### ISSUE TITLE
Error trying to run flood.py

### ISSUE THREAD

**Issue by SirFireball3521** [msemple1111/kahoot-hack#31]
When I try to run flood.py, I get the following error. I can confirm that the game exists, my friend had it running on his computer. I tried running it again after him closing the game, and received the same error.

`Traceback (most recent call last):`
    `File "flood.py", line 11, in <module>`
        `from main import kahoot`
    `File "/home/(my username)/kahoot-hack/main.py", line 11, in <module>`
        `import urllib.parse`
`ImportError: No module named parse`

**Comment by Hugo22O** [comment]
Are you sure you are using python 3? Try navigating to the folder where the flood.py file is located, then execute "py flood.py" without the "". 

Let me know if it works

Kind regards,
Hugo.

**Comment by SirFireball3521** [comment]
It says that the command "py" is not found. "python" command works to run it, but it still returns that same error.

**Comment by Hugo22O** [comment]
Try navigating to where flood.py is located, and then just do "flood.py".

**Comment by SirFireball3521** [comment]
`bash: flood.py: command not found` That only works with shell files
