### ISSUE TITLE
Can no longer answer questions.

### ISSUE THREAD

**Issue by michaelshumshum** [msemple1111/kahoot-hack#35]
For all the `do_id_#` functions, the `dataContent` has been changed. 
- `answerMap` is no longer present for id 2.
- `correctAnswers` is no longer present for id 8.
Because `answerMap` doesn't exist, we can't send any answers. There are also additional things that have been changed, such as `points`, but that has just been changed to `questionPoints`.

Some notes:
Now there is `quzQuestionAnswers` that I suspect is supposed to provide us with the correct answers for the entire kahoot, though I don't know what the individual numbers actually correspond to. It gives us a list of numbers, but I don't see any correlation.

**Comment by theusaf** [comment]
`quizQuestionAnswers`
> A list of numbers stating how many answers are in each question.
> https://kahoot.js.org/enum/LiveEventQuizStart
