### ISSUE TITLE
'game does not exist with that pin'

### ISSUE THREAD

**Issue by wc1202** [msemple1111/kahoot-hack#4]
i've tried both flood.py and play.py and each time i enter a pin they say a game with that pin doesn't exist

screenshot below
![image](https://cloud.githubusercontent.com/assets/6416201/20082095/b85059f8-a521-11e6-963e-2152738b1574.png)

**Comment by msemple1111** [comment]
It looks like kahoot have added a challenge to make it harder for bots to join games. Fortunately the challenge is only simple maths so i will have it working soon.

**Comment by msemple1111** [comment]
Yes, Kahoot are trying to make it difficult by changing up their session cookie system. It is getting complicated but ill have it fixed soon

**Comment by unixpickle** [comment]
@msemple1111 my [working implementation](https://github.com/unixpickle/kahoot-hack/blob/f77408b894361af231ab0cd01ebbf8928aee5351/kahoot/sessions.go#L38) would probably serve as a useful reference. I had to read kahoot's obfuscated JavaScript to figure out what they were up to.

**Comment by msemple1111** [comment]
@unixpickle what exactly is line [57-59](https://github.com/unixpickle/kahoot-hack/blob/f77408b894361af231ab0cd01ebbf8928aee5351/kahoot/sessions.go#L57-L59) doing?

Lets say i have the result of the challenge and the raw "x-kahoot-session-token", what is happening to get the resulting working session token?

**Comment by unixpickle** [comment]
So we base64 decode the x-kahoot-session-token, leaving us with a nasty string of bytes--for example, say {0x11, 0x22, 0x33, 0x44, 0x55}. We solve the challenge, giving us a string of bytes like "123" (written in ASCII as {0x31, 0x32, 0x33}).

We then compute the final session token by [XOR](https://en.wikipedia.org/wiki/Exclusive_or)-ing the challenge's bytes with the bytes of the base64-decoded token (challenge's bytes in italics):

{0x11 ^ *0x31*, 0x22 ^ *0x32*, 0x33 ^ *0x33*, 0x44 ^ *0x31*, 0x55 ^ *0x32*, ...}

The session token is a lot longer than the result of the challenge, so we have to repeat the challenge's bytes multiple times&mdash;once we get to the end of it, we go back to the beginning, hence the `%` (modulus).

**Comment by msemple1111** [comment]
Thanks @unixpickle for the reference, all working.

**Comment by msemple1111** [comment]
fixed #0e04539
