### ISSUE TITLE
[Bug] (Have a simple fix) 'challenge' Variable not Defined

### ISSUE THREAD

**Issue by lucadenhez** [msemple1111/kahoot-hack#40]
Hello, for the first time when running 'play.py', I got error code 909. I modified the code to show the exception, and it said 'challenge is not defined'. I looked at the method 'solve_kahoot_challenge' and you're trying to pass 'dataChallenge', but all the variables within it are using the variable 'challenge'. So yeah I just changed 'dataChallenge' to 'challenge' and it works like a charm! This code is awesome btw. And sorry If this isn't a formal bug report, I've never made one on GitHub before.

**Comment by chris-thorpe3db** [comment]
Fork the repo, open a pull request! He might merge it.

**Comment by msemple1111** [comment]
merged PR containing fix
