### ISSUE TITLE
Problem when running any of the python scripts

### ISSUE THREAD

**Issue by FazeDank001** [msemple1111/kahoot-hack#8]
When I try to run any of the python scripts it returns an error saying
`import urllib.parse
ImportError: No module named parse`
I am using MacOS 10.12.3 beta (16D25a)

**Comment by msemple1111** [comment]
I don't think you have installed python 3.

start by installing [homwbrew](http://brew.sh/#install)

then run `$ brew install python3`

then run the program by `python3 flood.py name 195657 50`

**Comment by msemple1111** [comment]
I'm going to close this issue now but if you still need help, please just enter a comment.

**Comment by FazeDank001** [comment]
The second command you sent (`python3 flood.py name 195657 50`) worked. I didn't know how I had to fill in the pin, name and bot count. Thanks!

**Comment by msemple1111** [comment]
you don't have to enter the name, ion and bot count but it saves having to enter it manually each time
