### ISSUE TITLE
Game does not exists with that pin

### ISSUE THREAD

**Issue by nedla2004** [msemple1111/kahoot-hack#9]
Whenever I try to use any of the tools, even when I know I am getting the pin right, the code just says `Game does not exists with that pin`. Is there a way for me to fix this?

**Comment by msemple1111** [comment]
Do you have a proper internet connection? Are you in a firewalled network?

**Comment by ElliotGluck** [comment]
You should double check you have all your dependencies installed.

**Comment by msemple1111** [comment]
There are no real dependencies to install now, only python 3. Requests is now included in the repo.

**Comment by jonkootje** [comment]
The script works fine for me on my desktop. The second i run it on my raspberry pi it gives the same error. In the log it says Error: 909 'no game with pin' please help :D

**Comment by msemple1111** [comment]
This error is to do with the program not being able to connect to the game. What happens if you run `ping 8.8.8.8`?

**Comment by jonkootje** [comment]
http://prntscr.com/e64b3y <-- this happends

**Comment by msemple1111** [comment]
have you tried running the program with sudo?

**Comment by jonkootje** [comment]
yapp, does not help

**Comment by msemple1111** [comment]
what is in your 'log.txt'

**Comment by jonkootje** [comment]
http://prntscr.com/e64b3y

**Comment by msemple1111** [comment]
thats the same screenshot as the ping

**Comment by jonkootje** [comment]
No i changed it, its the right one now

**Comment by msemple1111** [comment]
its the same on my end

**Comment by jonkootje** [comment]
huh weird. Well it only gives "Error no: 909 No kahoot Game with that pin"

**Comment by jonkootje** [comment]
It fails when i try to ping to www.kahoot.it

**Comment by jonkootje** [comment]
http://prntscr.com/e666eh <-- this might be interesting. When i run the test.py it gives me the following error, seems like the kahoot api gives a 403 error

**Comment by ElliotGluck** [comment]
Is your Pi running through some sort of VPN or firewall? My guess is that either your machine is blocking access to Kahoot's servers or vice versa.

**Comment by ElliotGluck** [comment]
I am not an expert but perhaps Raspbian is blocking your access.

**Comment by jonkootje** [comment]
It had to do with the version of python. I changed some syntax and it now kinda works. It only takes a long time before the users join.

**Comment by msemple1111** [comment]
The slow time is expected, i am working on a faster version currently.
The version of python is a simple mistake to make!
